### ISSUE TITLE
Banco de dados de usuário

### ISSUE THREAD

**Issue by Nathtruyts** [ProManage-FatecSJC/pro-manager-back#13]
Descrição: Criar um banco de dados (relacional ou não), para armazenar registros de usuário.

Peso: 3

D.O.D: 

- [ ] Dados de usuários registrados
- [ ] Campos definidos na modelagem presentes (Nome, usuário, email, senha, função)

**Comment by annakks** [comment]
inicio 20/03

**Comment by annakks** [comment]
fim 20/03
