### ISSUE TITLE
Criação do Banco de Dados  (Back-end)

### ISSUE THREAD

**Issue by bruno-pisciotta281** [ProManage-FatecSJC/pro-manager-back#8]
Descrição: Criação do Banco de Dados com base na modelagem já feita

D.O.D:

- [x] Tabelas criadas
- [x] Relacionamentos feitos
- [ ] Campos adicionados

Peso: 3

**Comment by annakks** [comment]
Tabelas e relacionamentos feitos, estou com problema para gerar as migrations
